steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/petclinic:$SHORT_SHA','-t', 'gcr.io/$PROJECT_ID/petclinic:${_DEPLOY_TAG}', '.' ]
    id: buildImage
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','-r','public/assets', 'gs://petclinic-assets-bucket/']
    id: 'copyAssetsToBucket'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['delete','-f','k8s/migratedb.yaml']
    id: 'deleteMigrateJob'
    waitFor: ['copyAssetsToBucket']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply','-f','k8s/migratedb.yaml']
    id: 'createMigrateJob'
    waitFor: ['deleteMigrateJob']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
  - name: gcr.io/$PROJECT_ID/kubectl_wait_for_job
    args: ['migratedb']
    waitFor: ['createMigrateJob']
    id: 'waitForMigrate'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set','image','deployment/petclinic','petclinic=gcr.io/$PROJECT_ID/petclinic:${_DEPLOY_TAG}']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
    waitFor: ['waitForMigrate']
images: ['gcr.io/$PROJECT_ID/petclinic:$SHORT_SHA','gcr.io/$PROJECT_ID/petclinic:${_DEPLOY_TAG}']