steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/petclinic:latest', '.' ]
    id: buildImage
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','-r','public/assets', 'gs://petclinic-assets-bucket/']
    id: 'copyAssetsToBucket'
images: ['gcr.io/$PROJECT_ID/petclinic:latest']