apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: us.gcr.io/next-2018-zero-to-prod/spring-petclinic
    docker:
      dockerfilePath: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: next-2018-zero-to-prod