apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic
  sessionAffinity: None
  type: LoadBalancer